wallpaper {
    monitor = DP-1
    path = $HOME/.config/wallpaper/wallpaper.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = $HOME/.config/wallpaper/wallpaper.png
    fit_mode = cover
}
