[mgr]
sort_by = "natural"
linemode = "size"
show_hidden = true
show_symlink = true

[preview]
max_width = 800
max_height = 800
image_delay = 100

[opener]
play = [ { run = 'mpv "$@"', orphan = true } ]
edit = [ { run = 'nvim "$@"', block = true } ]
